package CallCenter;

public enum Provincias {
	MISIONES, FORMOSA, JUJUY, SALTA, TUCUMAN, SANTIAGOESTERO,
	CHACO,NEUQUEN,SANTAFE,BUENOSAIRES,ENTRERIOS,
	CORRIENTES,CORDOBA,LARIOJA,LAPAMPA,RIONEGRO,SANTACRUZ,CHUBUT,
	TIERRADELFUEGO,MENDOZA,SANLUIS,SANJUAN,CATAMARCA,

}
